name: sos_info
description: SOS Rescue App
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  telephony: ^0.2.0
  permission_handler: ^11.0.0
  http: ^1.0.0
  webview_flutter: ^4.4.0
  shared_preferences: ^2.2.0
  google_generative_ai: ^0.4.0
  geolocator: ^11.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true